/* eslint-disable */
// Auto-generated by scripts/generate-products.mjs — do not edit manually
import type { Product, ProductCategory } from "@/types/product";

export const productCategories: ProductCategory[] = [
  {
    "slug": "bath-accessories",
    "name": "Bath Accessories"
  },
  {
    "slug": "bedding",
    "name": "Bedding"
  },
  {
    "slug": "carpet",
    "name": "Carpets"
  },
  {
    "slug": "chairs",
    "name": "Chairs"
  },
  {
    "slug": "curtains-blinds",
    "name": "Curtains & Blinds"
  },
  {
    "slug": "mats",
    "name": "Mats"
  },
  {
    "slug": "mattress",
    "name": "Mattresses"
  },
  {
    "slug": "sofas",
    "name": "Sofas"
  },
  {
    "slug": "tables",
    "name": "Tables"
  },
  {
    "slug": "wallpapers",
    "name": "Wallpapers"
  }
];

export const products: Product[] = [
  {
    "id": "1",
    "slug": "mattress-hybrid",
    "name": "Hybrid",
    "category": "Mattresses",
    "categorySlug": "mattress",
    "description": "Curated hybrid from our Mattresses collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Memory Foam",
    "dimensions": "72″ × 72″ (custom available)",
    "featured": true,
    "images": [
      "/images/products/Mettress/Hybrid.png"
    ],
    "folder": "Mettress",
    "style": "Modern",
    "price": null,
    "tags": [
      "Mattresses",
      "mattress"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "2",
    "slug": "mattress-mettresses",
    "name": "Mettresses",
    "category": "Mattresses",
    "categorySlug": "mattress",
    "description": "Curated mettresses from our Mattresses collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Spring",
    "dimensions": "72″ × 72″ (custom available)",
    "featured": true,
    "images": [
      "/images/products/Mettress/Mettresses.png"
    ],
    "folder": "Mettress",
    "style": "Classic",
    "price": null,
    "tags": [
      "Mattresses",
      "mattress"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "3",
    "slug": "mattress-foam",
    "name": "foam",
    "category": "Mattresses",
    "categorySlug": "mattress",
    "description": "Curated foam from our Mattresses collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Hybrid Foam",
    "dimensions": "72″ × 72″ (custom available)",
    "featured": false,
    "images": [
      "/images/products/Mettress/foam.png"
    ],
    "folder": "Mettress",
    "style": "Contemporary",
    "price": null,
    "tags": [
      "Mattresses",
      "mattress"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "4",
    "slug": "mattress-memory",
    "name": "memory",
    "category": "Mattresses",
    "categorySlug": "mattress",
    "description": "Curated memory from our Mattresses collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Memory Foam",
    "dimensions": "72″ × 72″ (custom available)",
    "featured": false,
    "images": [
      "/images/products/Mettress/memory.png"
    ],
    "folder": "Mettress",
    "style": "Minimal",
    "price": null,
    "tags": [
      "Mattresses",
      "mattress"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "5",
    "slug": "mattress-spring",
    "name": "spring",
    "category": "Mattresses",
    "categorySlug": "mattress",
    "description": "Curated spring from our Mattresses collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Spring",
    "dimensions": "72″ × 72″ (custom available)",
    "featured": false,
    "images": [
      "/images/products/Mettress/spring.png"
    ],
    "folder": "Mettress",
    "style": "Editorial",
    "price": null,
    "tags": [
      "Mattresses",
      "mattress"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "6",
    "slug": "sofas-lawson",
    "name": "Lawson",
    "category": "Sofas",
    "categorySlug": "sofas",
    "description": "Curated lawson from our Sofas collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Premium Fabric",
    "dimensions": "6′ × 8′ sectional",
    "featured": true,
    "images": [
      "/images/products/Sofas/Lawson.png"
    ],
    "folder": "Sofas",
    "style": "Modern",
    "price": null,
    "tags": [
      "Sofas",
      "sofas"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "7",
    "slug": "sofas-modern",
    "name": "Modern",
    "category": "Sofas",
    "categorySlug": "sofas",
    "description": "Curated modern from our Sofas collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Velvet",
    "dimensions": "6′ × 8′ sectional",
    "featured": true,
    "images": [
      "/images/products/Sofas/Modern.png"
    ],
    "folder": "Sofas",
    "style": "Classic",
    "price": null,
    "tags": [
      "Sofas",
      "sofas"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "8",
    "slug": "sofas-recliner",
    "name": "Recliner",
    "category": "Sofas",
    "categorySlug": "sofas",
    "description": "Curated recliner from our Sofas collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Linen Fabric",
    "dimensions": "6′ × 8′ sectional",
    "featured": false,
    "images": [
      "/images/products/Sofas/Recliner.png"
    ],
    "folder": "Sofas",
    "style": "Contemporary",
    "price": null,
    "tags": [
      "Sofas",
      "sofas"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "9",
    "slug": "tables-tea-table",
    "name": "Tea table",
    "category": "Tables",
    "categorySlug": "tables",
    "description": "Curated tea table from our Tables collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Laminate",
    "dimensions": "48″ × 24″",
    "featured": true,
    "images": [
      "/images/products/Tables/Tea table.png"
    ],
    "folder": "Tables",
    "style": "Minimal",
    "price": null,
    "tags": [
      "Tables",
      "tables"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "10",
    "slug": "tables-table-cover-1",
    "name": "table_cover 1",
    "category": "Tables",
    "categorySlug": "tables",
    "description": "Curated table_cover 1 from our Tables collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Wood",
    "dimensions": "48″ × 24″",
    "featured": true,
    "images": [
      "/images/products/Tables/table_cover 1.png"
    ],
    "folder": "Tables",
    "style": "Editorial",
    "price": null,
    "tags": [
      "Tables",
      "tables"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "11",
    "slug": "tables-table-cover-2",
    "name": "table_cover 2",
    "category": "Tables",
    "categorySlug": "tables",
    "description": "Curated table_cover 2 from our Tables collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Glass & Wood",
    "dimensions": "48″ × 24″",
    "featured": false,
    "images": [
      "/images/products/Tables/table_cover 2.png"
    ],
    "folder": "Tables",
    "style": "Modern",
    "price": null,
    "tags": [
      "Tables",
      "tables"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "12",
    "slug": "bath-accessories-bath-and-hand-towel",
    "name": "bath & hand towel",
    "category": "Bath Accessories",
    "categorySlug": "bath-accessories",
    "description": "Curated bath & hand towel from our Bath Accessories collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Polyester",
    "dimensions": "Standard bath size",
    "featured": true,
    "images": [
      "/images/products/bath accesories/bath & hand towel.png"
    ],
    "folder": "bath accesories",
    "style": "Classic",
    "price": null,
    "tags": [
      "Bath Accessories",
      "bath-accessories"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "13",
    "slug": "bath-accessories-shower-curtain",
    "name": "shower curtain",
    "category": "Bath Accessories",
    "categorySlug": "bath-accessories",
    "description": "Curated shower curtain from our Bath Accessories collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Cotton",
    "dimensions": "Standard bath size",
    "featured": true,
    "images": [
      "/images/products/bath accesories/shower curtain.png"
    ],
    "folder": "bath accesories",
    "style": "Contemporary",
    "price": null,
    "tags": [
      "Bath Accessories",
      "bath-accessories"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "14",
    "slug": "bath-accessories-shower-mat",
    "name": "shower mat",
    "category": "Bath Accessories",
    "categorySlug": "bath-accessories",
    "description": "Curated shower mat from our Bath Accessories collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Microfiber",
    "dimensions": "Standard bath size",
    "featured": false,
    "images": [
      "/images/products/bath accesories/shower mat.png"
    ],
    "folder": "bath accesories",
    "style": "Minimal",
    "price": null,
    "tags": [
      "Bath Accessories",
      "bath-accessories"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "15",
    "slug": "bedding-bed-sheet",
    "name": "bed sheet",
    "category": "Bedding",
    "categorySlug": "bedding",
    "description": "Curated bed sheet from our Bedding collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Microfiber",
    "dimensions": "King / Queen compatible",
    "featured": true,
    "images": [
      "/images/products/bedding/bed sheet.png"
    ],
    "folder": "bedding",
    "style": "Editorial",
    "price": null,
    "tags": [
      "Bedding",
      "bedding"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "16",
    "slug": "bedding-blankets",
    "name": "blankets",
    "category": "Bedding",
    "categorySlug": "bedding",
    "description": "Curated blankets from our Bedding collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Cotton",
    "dimensions": "King / Queen compatible",
    "featured": true,
    "images": [
      "/images/products/bedding/blankets.png"
    ],
    "folder": "bedding",
    "style": "Modern",
    "price": null,
    "tags": [
      "Bedding",
      "bedding"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "17",
    "slug": "bedding-comforter-set",
    "name": "comforter set",
    "category": "Bedding",
    "categorySlug": "bedding",
    "description": "Curated comforter set from our Bedding collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Linen Blend",
    "dimensions": "King / Queen compatible",
    "featured": false,
    "images": [
      "/images/products/bedding/comforter set.png"
    ],
    "folder": "bedding",
    "style": "Classic",
    "price": null,
    "tags": [
      "Bedding",
      "bedding"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "18",
    "slug": "bedding-mettress-protector",
    "name": "mettress protector",
    "category": "Bedding",
    "categorySlug": "bedding",
    "description": "Curated mettress protector from our Bedding collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Microfiber",
    "dimensions": "King / Queen compatible",
    "featured": false,
    "images": [
      "/images/products/bedding/mettress protector.png"
    ],
    "folder": "bedding",
    "style": "Contemporary",
    "price": null,
    "tags": [
      "Bedding",
      "bedding"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "19",
    "slug": "carpet-loop-pile",
    "name": "Loop pile",
    "category": "Carpets",
    "categorySlug": "carpet",
    "description": "Curated loop pile from our Carpets collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Wool Blend",
    "dimensions": "Custom sizing available",
    "featured": true,
    "images": [
      "/images/products/carpet/Loop pile.png"
    ],
    "folder": "carpet",
    "style": "Minimal",
    "price": null,
    "tags": [
      "Carpets",
      "carpet"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "20",
    "slug": "carpet-pvc",
    "name": "PVC",
    "category": "Carpets",
    "categorySlug": "carpet",
    "description": "Curated pvc from our Carpets collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "PVC",
    "dimensions": "Custom sizing available",
    "featured": true,
    "images": [
      "/images/products/carpet/PVC.png"
    ],
    "folder": "carpet",
    "style": "Editorial",
    "price": null,
    "tags": [
      "Carpets",
      "carpet"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "21",
    "slug": "carpet-center-galicho",
    "name": "center galicho",
    "category": "Carpets",
    "categorySlug": "carpet",
    "description": "Curated center galicho from our Carpets collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Polypropylene",
    "dimensions": "Custom sizing available",
    "featured": false,
    "images": [
      "/images/products/carpet/center galicho.png"
    ],
    "folder": "carpet",
    "style": "Modern",
    "price": null,
    "tags": [
      "Carpets",
      "carpet"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "22",
    "slug": "chairs-decorative-chairs",
    "name": "decorative chairs",
    "category": "Chairs",
    "categorySlug": "chairs",
    "description": "Curated decorative chairs from our Chairs collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Fabric",
    "dimensions": "32″ W × 34″ D × 36″ H",
    "featured": true,
    "images": [
      "/images/products/chairs/decorative chairs.png"
    ],
    "folder": "chairs",
    "style": "Classic",
    "price": null,
    "tags": [
      "Chairs",
      "chairs"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "23",
    "slug": "curtains-blinds-american-curtain",
    "name": "American Curtain",
    "category": "Curtains & Blinds",
    "categorySlug": "curtains-blinds",
    "description": "Curated american curtain from our Curtains & Blinds collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Blackout Fabric",
    "dimensions": "Made to measure",
    "featured": true,
    "images": [
      "/images/products/curtains & blinds/American Curtain.png"
    ],
    "folder": "curtains & blinds",
    "style": "Contemporary",
    "price": null,
    "tags": [
      "Curtains & Blinds",
      "curtains-blinds"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "24",
    "slug": "curtains-blinds-arabian-cunrtain",
    "name": "Arabian cunrtain",
    "category": "Curtains & Blinds",
    "categorySlug": "curtains-blinds",
    "description": "Curated arabian cunrtain from our Curtains & Blinds collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Sheer Blend",
    "dimensions": "Made to measure",
    "featured": true,
    "images": [
      "/images/products/curtains & blinds/Arabian cunrtain.png"
    ],
    "folder": "curtains & blinds",
    "style": "Minimal",
    "price": null,
    "tags": [
      "Curtains & Blinds",
      "curtains-blinds"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "25",
    "slug": "curtains-blinds-eyelet-curtein",
    "name": "Eyelet Curtein",
    "category": "Curtains & Blinds",
    "categorySlug": "curtains-blinds",
    "description": "Curated eyelet curtein from our Curtains & Blinds collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Polyester",
    "dimensions": "Made to measure",
    "featured": false,
    "images": [
      "/images/products/curtains & blinds/Eyelet Curtein.png"
    ],
    "folder": "curtains & blinds",
    "style": "Editorial",
    "price": null,
    "tags": [
      "Curtains & Blinds",
      "curtains-blinds"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "26",
    "slug": "curtains-blinds-roller-blinds",
    "name": "Roller Blinds",
    "category": "Curtains & Blinds",
    "categorySlug": "curtains-blinds",
    "description": "Curated roller blinds from our Curtains & Blinds collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Blackout Fabric",
    "dimensions": "Made to measure",
    "featured": false,
    "images": [
      "/images/products/curtains & blinds/Roller Blinds.png"
    ],
    "folder": "curtains & blinds",
    "style": "Modern",
    "price": null,
    "tags": [
      "Curtains & Blinds",
      "curtains-blinds"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "27",
    "slug": "curtains-blinds-roman-blinds",
    "name": "Roman Blinds",
    "category": "Curtains & Blinds",
    "categorySlug": "curtains-blinds",
    "description": "Curated roman blinds from our Curtains & Blinds collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Sheer Blend",
    "dimensions": "Made to measure",
    "featured": false,
    "images": [
      "/images/products/curtains & blinds/Roman Blinds.png"
    ],
    "folder": "curtains & blinds",
    "style": "Classic",
    "price": null,
    "tags": [
      "Curtains & Blinds",
      "curtains-blinds"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "28",
    "slug": "mats-bath",
    "name": "bath",
    "category": "Mats",
    "categorySlug": "mats",
    "description": "Curated bath from our Mats collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Rubber",
    "dimensions": "Multiple sizes in-store",
    "featured": true,
    "images": [
      "/images/products/mats/floor mats/bath.png"
    ],
    "folder": "mats/floor mats",
    "style": "Contemporary",
    "price": null,
    "tags": [
      "Mats",
      "mats",
      "floor-mats"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "29",
    "slug": "mats-cushion",
    "name": "cushion",
    "category": "Mats",
    "categorySlug": "mats",
    "description": "Curated cushion from our Mats collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Grass Fiber",
    "dimensions": "Multiple sizes in-store",
    "featured": true,
    "images": [
      "/images/products/mats/floor mats/cushion.png"
    ],
    "folder": "mats/floor mats",
    "style": "Minimal",
    "price": null,
    "tags": [
      "Mats",
      "mats",
      "floor-mats"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "30",
    "slug": "mats-kitchen",
    "name": "kitchen",
    "category": "Mats",
    "categorySlug": "mats",
    "description": "Curated kitchen from our Mats collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Memory Foam",
    "dimensions": "Multiple sizes in-store",
    "featured": false,
    "images": [
      "/images/products/mats/floor mats/kitchen.png"
    ],
    "folder": "mats/floor mats",
    "style": "Editorial",
    "price": null,
    "tags": [
      "Mats",
      "mats",
      "floor-mats"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "31",
    "slug": "mats-snake",
    "name": "snake",
    "category": "Mats",
    "categorySlug": "mats",
    "description": "Curated snake from our Mats collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Rubber",
    "dimensions": "Multiple sizes in-store",
    "featured": false,
    "images": [
      "/images/products/mats/floor mats/snake.png"
    ],
    "folder": "mats/floor mats",
    "style": "Modern",
    "price": null,
    "tags": [
      "Mats",
      "mats",
      "floor-mats"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "32",
    "slug": "mats-yoga",
    "name": "yoga",
    "category": "Mats",
    "categorySlug": "mats",
    "description": "Curated yoga from our Mats collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Grass Fiber",
    "dimensions": "Multiple sizes in-store",
    "featured": false,
    "images": [
      "/images/products/mats/floor mats/yoga.png"
    ],
    "folder": "mats/floor mats",
    "style": "Classic",
    "price": null,
    "tags": [
      "Mats",
      "mats",
      "floor-mats"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "33",
    "slug": "mats-artificial-plants",
    "name": "artificial plants",
    "category": "Mats",
    "categorySlug": "mats",
    "description": "Curated artificial plants from our Mats collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Memory Foam",
    "dimensions": "Multiple sizes in-store",
    "featured": false,
    "images": [
      "/images/products/mats/grass mats/artificial plants.png"
    ],
    "folder": "mats/grass mats",
    "style": "Contemporary",
    "price": null,
    "tags": [
      "Mats",
      "mats",
      "grass-mats"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "34",
    "slug": "mats-grass-tiles",
    "name": "grass tiles",
    "category": "Mats",
    "categorySlug": "mats",
    "description": "Curated grass tiles from our Mats collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Rubber",
    "dimensions": "Multiple sizes in-store",
    "featured": false,
    "images": [
      "/images/products/mats/grass mats/grass tiles.png"
    ],
    "folder": "mats/grass mats",
    "style": "Minimal",
    "price": null,
    "tags": [
      "Mats",
      "mats",
      "grass-mats"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "35",
    "slug": "mats-grass",
    "name": "grass",
    "category": "Mats",
    "categorySlug": "mats",
    "description": "Curated grass from our Mats collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Grass Fiber",
    "dimensions": "Multiple sizes in-store",
    "featured": false,
    "images": [
      "/images/products/mats/grass mats/grass.png"
    ],
    "folder": "mats/grass mats",
    "style": "Editorial",
    "price": null,
    "tags": [
      "Mats",
      "mats",
      "grass-mats"
    ],
    "whatsappNumber": "919081622516"
  },
  {
    "id": "36",
    "slug": "wallpapers-digital",
    "name": "digital",
    "category": "Wallpapers",
    "categorySlug": "wallpapers",
    "description": "Curated digital from our Wallpapers collection — crafted for refined interiors with lasting comfort and editorial presence.",
    "material": "Textured Paper",
    "dimensions": "Roll — 53 cm × 10 m",
    "featured": true,
    "images": [
      "/images/products/wallpapers/digital.png"
    ],
    "folder": "wallpapers",
    "style": "Modern",
    "price": null,
    "tags": [
      "Wallpapers",
      "wallpapers"
    ],
    "whatsappNumber": "919081622516"
  }
];

export const featuredProducts = products.filter((p) => p.featured);
